/**
 * Ahava Error Codes — Comprehensive registry of all application errors
 * Used for API responses, logging, and client-side error handling
 */

export enum AhavaErrorCode {
  // AUTHENTICATION (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_PIN_INCORRECT = "AUTH_PIN_INCORRECT",
  AUTH_PIN_LOCKED = "AUTH_PIN_LOCKED",
  AUTH_PIN_ATTEMPTS_EXCEEDED = "AUTH_PIN_ATTEMPTS_EXCEEDED",
  AUTH_DEVICE_NOT_BOUND = "AUTH_DEVICE_NOT_BOUND",
  AUTH_DEVICE_MISMATCH = "AUTH_DEVICE_MISMATCH",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_REVOKED = "AUTH_TOKEN_REVOKED",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_BIOMETRIC_ENROLLMENT_REQUIRED = "AUTH_BIOMETRIC_ENROLLMENT_REQUIRED",
  AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",

  // KYC (KYC_xxx)
  KYC_TIER_MISMATCH = "KYC_TIER_MISMATCH",
  KYC_TIER_EXCEEDED = "KYC_TIER_EXCEEDED",
  KYC_PENDING = "KYC_PENDING",
  KYC_DOCUMENT_INVALID = "KYC_DOCUMENT_INVALID",
  KYC_DOCUMENT_EXPIRED = "KYC_DOCUMENT_EXPIRED",
  KYC_VERIFICATION_REQUIRED = "KYC_VERIFICATION_REQUIRED",
  KYC_LIMIT_DAILY_EXCEEDED = "KYC_LIMIT_DAILY_EXCEEDED",
  KYC_LIMIT_MONTHLY_EXCEEDED = "KYC_LIMIT_MONTHLY_EXCEEDED",
  KYC_LIMIT_BALANCE_EXCEEDED = "KYC_LIMIT_BALANCE_EXCEEDED",
  KYC_LIMIT_PER_TRANSACTION_EXCEEDED = "KYC_LIMIT_PER_TRANSACTION_EXCEEDED",
  KYC_MINOR_NOT_ALLOWED = "KYC_MINOR_NOT_ALLOWED",
  KYC_GUARDIAN_APPROVAL_REQUIRED = "KYC_GUARDIAN_APPROVAL_REQUIRED",

  // WALLET (WAL_xxx)
  WAL_NOT_FOUND = "WAL_NOT_FOUND",
  WAL_INSUFFICIENT_BALANCE = "WAL_INSUFFICIENT_BALANCE",
  WAL_WALLET_SUSPENDED = "WAL_WALLET_SUSPENDED",
  WAL_WALLET_FROZEN = "WAL_WALLET_FROZEN",
  WAL_WALLET_CLOSED = "WAL_WALLET_CLOSED",
  WAL_INVALID_TYPE = "WAL_INVALID_TYPE",
  WAL_INVALID_STATUS = "WAL_INVALID_STATUS",
  WAL_CURRENCY_MISMATCH = "WAL_CURRENCY_MISMATCH",
  WAL_PENDING_BALANCE_EXCEEDS_LIMIT = "WAL_PENDING_BALANCE_EXCEEDS_LIMIT",
  WAL_RESERVED_BALANCE_CONFLICT = "WAL_RESERVED_BALANCE_CONFLICT",

  // PAYMENT (PAY_xxx)
  PAY_NOT_FOUND = "PAY_NOT_FOUND",
  PAY_INVALID_AMOUNT = "PAY_INVALID_AMOUNT",
  PAY_AMOUNT_ZERO = "PAY_AMOUNT_ZERO",
  PAY_AMOUNT_NEGATIVE = "PAY_AMOUNT_NEGATIVE",
  PAY_DUPLICATE_IDEMPOTENCY_KEY = "PAY_DUPLICATE_IDEMPOTENCY_KEY",
  PAY_IDEMPOTENCY_CONFLICT = "PAY_IDEMPOTENCY_CONFLICT",
  PAY_COUNTERPARTY_NOT_FOUND = "PAY_COUNTERPARTY_NOT_FOUND",
  PAY_COUNTERPARTY_WALLET_CLOSED = "PAY_COUNTERPARTY_WALLET_CLOSED",
  PAY_INVALID_METHOD = "PAY_INVALID_METHOD",
  PAY_METHOD_NOT_AVAILABLE = "PAY_METHOD_NOT_AVAILABLE",
  PAY_PAYSHAP_UNAVAILABLE = "PAY_PAYSHAP_UNAVAILABLE",
  PAY_PAYSHAP_REJECTED = "PAY_PAYSHAP_REJECTED",
  PAY_PAYSHAP_TIMEOUT = "PAY_PAYSHAP_TIMEOUT",
  PAY_INVALID_FEE_STRUCTURE = "PAY_INVALID_FEE_STRUCTURE",
  PAY_FEE_POOL_INSUFFICIENT = "PAY_FEE_POOL_INSUFFICIENT",
  PAY_REVERSAL_NOT_ALLOWED = "PAY_REVERSAL_NOT_ALLOWED",
  PAY_ALREADY_REVERSED = "PAY_ALREADY_REVERSED",
  PAY_TIMEOUT = "PAY_TIMEOUT",
  PAY_FAILED = "PAY_FAILED",

  // QR (QR_xxx)
  QR_NOT_FOUND = "QR_NOT_FOUND",
  QR_EXPIRED = "QR_EXPIRED",
  QR_INACTIVE = "QR_INACTIVE",
  QR_MAX_USAGE_REACHED = "QR_MAX_USAGE_REACHED",
  QR_INVALID_PAYLOAD = "QR_INVALID_PAYLOAD",
  QR_INVALID_HASH = "QR_INVALID_HASH",
  QR_AMOUNT_MISMATCH = "QR_AMOUNT_MISMATCH",

  // AML (AML_xxx)
  AML_SANCTIONS_MATCH = "AML_SANCTIONS_MATCH",
  AML_PEP_FLAG = "AML_PEP_FLAG",
  AML_VELOCITY_VIOLATION = "AML_VELOCITY_VIOLATION",
  AML_ROUND_TRIP_DETECTED = "AML_ROUND_TRIP_DETECTED",
  AML_STRUCTURING_DETECTED = "AML_STRUCTURING_DETECTED",
  AML_GEO_ANOMALY = "AML_GEO_ANOMALY",
  AML_HIGHER_RISK_JURISDICTION = "AML_HIGHER_RISK_JURISDICTION",
  AML_TRANSACTION_BLOCKED = "AML_TRANSACTION_BLOCKED",
  AML_ACCOUNT_FROZEN = "AML_ACCOUNT_FROZEN",
  AML_STR_FILED = "AML_STR_FILED",
  AML_UNDER_REVIEW = "AML_UNDER_REVIEW",

  // NOTIFICATIONS (NOT_xxx)
  NOT_NOT_FOUND = "NOT_NOT_FOUND",
  NOT_CHANNEL_UNAVAILABLE = "NOT_CHANNEL_UNAVAILABLE",
  NOT_SEND_FAILED = "NOT_SEND_FAILED",
  NOT_DELIVERY_FAILED = "NOT_DELIVERY_FAILED",
  NOT_INVALID_RECIPIENT = "NOT_INVALID_RECIPIENT",
  NOT_FCM_UNAVAILABLE = "NOT_FCM_UNAVAILABLE",
  NOT_SMS_QUOTA_EXCEEDED = "NOT_SMS_QUOTA_EXCEEDED",
  NOT_EMAIL_INVALID = "NOT_EMAIL_INVALID",

  // RATE LIMITING & QUOTAS (RATE_xxx)
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  RATE_DEVICE_EXCEEDED = "RATE_DEVICE_EXCEEDED",
  RATE_LOGIN_ATTEMPTS_EXCEEDED = "RATE_LOGIN_ATTEMPTS_EXCEEDED",
  RATE_PAYMENT_ATTEMPTS_EXCEEDED = "RATE_PAYMENT_ATTEMPTS_EXCEEDED",
  RATE_SMS_QUOTA_EXCEEDED = "RATE_SMS_QUOTA_EXCEEDED",

  // VALIDATION (VAL_xxx)
  VAL_INVALID_INPUT = "VAL_INVALID_INPUT",
  VAL_INVALID_PHONE = "VAL_INVALID_PHONE",
  VAL_INVALID_EMAIL = "VAL_INVALID_EMAIL",
  VAL_INVALID_ID_NUMBER = "VAL_INVALID_ID_NUMBER",
  VAL_INVALID_UUID = "VAL_INVALID_UUID",
  VAL_INVALID_CURRENCY = "VAL_INVALID_CURRENCY",
  VAL_MISSING_REQUIRED_FIELD = "VAL_MISSING_REQUIRED_FIELD",
  VAL_INVALID_ENUM_VALUE = "VAL_INVALID_ENUM_VALUE",
  VAL_CONSTRAINT_VIOLATION = "VAL_CONSTRAINT_VIOLATION",

  // CONFLICT (CONFLICT_xxx)
  CONFLICT_USER_EXISTS = "CONFLICT_USER_EXISTS",
  CONFLICT_PHONE_ALREADY_REGISTERED = "CONFLICT_PHONE_ALREADY_REGISTERED",
  CONFLICT_EMAIL_ALREADY_REGISTERED = "CONFLICT_EMAIL_ALREADY_REGISTERED",
  CONFLICT_WALLET_EXISTS = "CONFLICT_WALLET_EXISTS",
  CONFLICT_AGENT_CODE_EXISTS = "CONFLICT_AGENT_CODE_EXISTS",
  CONFLICT_RESOURCE_MODIFIED = "CONFLICT_RESOURCE_MODIFIED",

  // EXTERNAL INTEGRATIONS (EXT_xxx)
  EXT_PAYSHAP_ERROR = "EXT_PAYSHAP_ERROR",
  EXT_COMPLY_ADVANTAGE_ERROR = "EXT_COMPLY_ADVANTAGE_ERROR",
  EXT_AFRICA_TALKING_ERROR = "EXT_AFRICA_TALKING_ERROR",
  EXT_FCM_ERROR = "EXT_FCM_ERROR",
  EXT_AWS_SECRETS_ERROR = "EXT_AWS_SECRETS_ERROR",
  EXT_S3_ERROR = "EXT_S3_ERROR",
  EXT_SES_ERROR = "EXT_SES_ERROR",

  // DATABASE (DB_xxx)
  DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED",
  DB_TRANSACTION_FAILED = "DB_TRANSACTION_FAILED",
  DB_DEADLOCK = "DB_DEADLOCK",
  DB_CONSTRAINT_VIOLATION = "DB_CONSTRAINT_VIOLATION",
  DB_NOT_FOUND = "DB_NOT_FOUND",
  DB_QUERY_TIMEOUT = "DB_QUERY_TIMEOUT",

  // INTERNAL (INTERNAL_xxx)
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INTERNAL_NOT_IMPLEMENTED = "INTERNAL_NOT_IMPLEMENTED",
  INTERNAL_SERVICE_UNAVAILABLE = "INTERNAL_SERVICE_UNAVAILABLE",
  INTERNAL_DEPENDENCY_FAILURE = "INTERNAL_DEPENDENCY_FAILURE",
  INTERNAL_CONFIG_ERROR = "INTERNAL_CONFIG_ERROR",
}

/**
 * HTTP status mapping for error codes
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<AhavaErrorCode, number> = {
  // 400 Bad Request
  [AhavaErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [AhavaErrorCode.AUTH_PIN_INCORRECT]: 401,
  [AhavaErrorCode.AUTH_PIN_LOCKED]: 429,
  [AhavaErrorCode.AUTH_PIN_ATTEMPTS_EXCEEDED]: 429,
  [AhavaErrorCode.AUTH_DEVICE_NOT_BOUND]: 400,
  [AhavaErrorCode.AUTH_DEVICE_MISMATCH]: 401,
  [AhavaErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [AhavaErrorCode.AUTH_INVALID_TOKEN]: 401,
  [AhavaErrorCode.AUTH_TOKEN_REVOKED]: 401,
  [AhavaErrorCode.AUTH_UNAUTHORIZED]: 403,
  [AhavaErrorCode.AUTH_BIOMETRIC_ENROLLMENT_REQUIRED]: 400,
  [AhavaErrorCode.AUTH_EMAIL_NOT_VERIFIED]: 400,

  [AhavaErrorCode.KYC_TIER_MISMATCH]: 400,
  [AhavaErrorCode.KYC_TIER_EXCEEDED]: 403,
  [AhavaErrorCode.KYC_PENDING]: 400,
  [AhavaErrorCode.KYC_DOCUMENT_INVALID]: 422,
  [AhavaErrorCode.KYC_DOCUMENT_EXPIRED]: 410,
  [AhavaErrorCode.KYC_VERIFICATION_REQUIRED]: 400,
  [AhavaErrorCode.KYC_LIMIT_DAILY_EXCEEDED]: 429,
  [AhavaErrorCode.KYC_LIMIT_MONTHLY_EXCEEDED]: 429,
  [AhavaErrorCode.KYC_LIMIT_BALANCE_EXCEEDED]: 400,
  [AhavaErrorCode.KYC_LIMIT_PER_TRANSACTION_EXCEEDED]: 429,
  [AhavaErrorCode.KYC_MINOR_NOT_ALLOWED]: 403,
  [AhavaErrorCode.KYC_GUARDIAN_APPROVAL_REQUIRED]: 403,

  [AhavaErrorCode.WAL_NOT_FOUND]: 404,
  [AhavaErrorCode.WAL_INSUFFICIENT_BALANCE]: 402,
  [AhavaErrorCode.WAL_WALLET_SUSPENDED]: 403,
  [AhavaErrorCode.WAL_WALLET_FROZEN]: 403,
  [AhavaErrorCode.WAL_WALLET_CLOSED]: 410,
  [AhavaErrorCode.WAL_INVALID_TYPE]: 400,
  [AhavaErrorCode.WAL_INVALID_STATUS]: 400,
  [AhavaErrorCode.WAL_CURRENCY_MISMATCH]: 400,
  [AhavaErrorCode.WAL_PENDING_BALANCE_EXCEEDS_LIMIT]: 400,
  [AhavaErrorCode.WAL_RESERVED_BALANCE_CONFLICT]: 409,

  [AhavaErrorCode.PAY_NOT_FOUND]: 404,
  [AhavaErrorCode.PAY_INVALID_AMOUNT]: 400,
  [AhavaErrorCode.PAY_AMOUNT_ZERO]: 400,
  [AhavaErrorCode.PAY_AMOUNT_NEGATIVE]: 400,
  [AhavaErrorCode.PAY_DUPLICATE_IDEMPOTENCY_KEY]: 409,
  [AhavaErrorCode.PAY_IDEMPOTENCY_CONFLICT]: 409,
  [AhavaErrorCode.PAY_COUNTERPARTY_NOT_FOUND]: 404,
  [AhavaErrorCode.PAY_COUNTERPARTY_WALLET_CLOSED]: 410,
  [AhavaErrorCode.PAY_INVALID_METHOD]: 400,
  [AhavaErrorCode.PAY_METHOD_NOT_AVAILABLE]: 503,
  [AhavaErrorCode.PAY_PAYSHAP_UNAVAILABLE]: 503,
  [AhavaErrorCode.PAY_PAYSHAP_REJECTED]: 402,
  [AhavaErrorCode.PAY_PAYSHAP_TIMEOUT]: 504,
  [AhavaErrorCode.PAY_INVALID_FEE_STRUCTURE]: 500,
  [AhavaErrorCode.PAY_FEE_POOL_INSUFFICIENT]: 500,
  [AhavaErrorCode.PAY_REVERSAL_NOT_ALLOWED]: 400,
  [AhavaErrorCode.PAY_ALREADY_REVERSED]: 409,
  [AhavaErrorCode.PAY_TIMEOUT]: 504,
  [AhavaErrorCode.PAY_FAILED]: 402,

  [AhavaErrorCode.QR_NOT_FOUND]: 404,
  [AhavaErrorCode.QR_EXPIRED]: 410,
  [AhavaErrorCode.QR_INACTIVE]: 400,
  [AhavaErrorCode.QR_MAX_USAGE_REACHED]: 400,
  [AhavaErrorCode.QR_INVALID_PAYLOAD]: 400,
  [AhavaErrorCode.QR_INVALID_HASH]: 400,
  [AhavaErrorCode.QR_AMOUNT_MISMATCH]: 400,

  [AhavaErrorCode.AML_SANCTIONS_MATCH]: 403,
  [AhavaErrorCode.AML_PEP_FLAG]: 403,
  [AhavaErrorCode.AML_VELOCITY_VIOLATION]: 429,
  [AhavaErrorCode.AML_ROUND_TRIP_DETECTED]: 403,
  [AhavaErrorCode.AML_STRUCTURING_DETECTED]: 403,
  [AhavaErrorCode.AML_GEO_ANOMALY]: 403,
  [AhavaErrorCode.AML_HIGHER_RISK_JURISDICTION]: 403,
  [AhavaErrorCode.AML_TRANSACTION_BLOCKED]: 403,
  [AhavaErrorCode.AML_ACCOUNT_FROZEN]: 403,
  [AhavaErrorCode.AML_STR_FILED]: 403,
  [AhavaErrorCode.AML_UNDER_REVIEW]: 403,

  [AhavaErrorCode.NOT_NOT_FOUND]: 404,
  [AhavaErrorCode.NOT_CHANNEL_UNAVAILABLE]: 503,
  [AhavaErrorCode.NOT_SEND_FAILED]: 500,
  [AhavaErrorCode.NOT_DELIVERY_FAILED]: 500,
  [AhavaErrorCode.NOT_INVALID_RECIPIENT]: 400,
  [AhavaErrorCode.NOT_FCM_UNAVAILABLE]: 503,
  [AhavaErrorCode.NOT_SMS_QUOTA_EXCEEDED]: 429,
  [AhavaErrorCode.NOT_EMAIL_INVALID]: 400,

  [AhavaErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [AhavaErrorCode.RATE_DEVICE_EXCEEDED]: 429,
  [AhavaErrorCode.RATE_LOGIN_ATTEMPTS_EXCEEDED]: 429,
  [AhavaErrorCode.RATE_PAYMENT_ATTEMPTS_EXCEEDED]: 429,
  [AhavaErrorCode.RATE_SMS_QUOTA_EXCEEDED]: 429,

  [AhavaErrorCode.VAL_INVALID_INPUT]: 400,
  [AhavaErrorCode.VAL_INVALID_PHONE]: 400,
  [AhavaErrorCode.VAL_INVALID_EMAIL]: 400,
  [AhavaErrorCode.VAL_INVALID_ID_NUMBER]: 400,
  [AhavaErrorCode.VAL_INVALID_UUID]: 400,
  [AhavaErrorCode.VAL_INVALID_CURRENCY]: 400,
  [AhavaErrorCode.VAL_MISSING_REQUIRED_FIELD]: 400,
  [AhavaErrorCode.VAL_INVALID_ENUM_VALUE]: 400,
  [AhavaErrorCode.VAL_CONSTRAINT_VIOLATION]: 400,

  [AhavaErrorCode.CONFLICT_USER_EXISTS]: 409,
  [AhavaErrorCode.CONFLICT_PHONE_ALREADY_REGISTERED]: 409,
  [AhavaErrorCode.CONFLICT_EMAIL_ALREADY_REGISTERED]: 409,
  [AhavaErrorCode.CONFLICT_WALLET_EXISTS]: 409,
  [AhavaErrorCode.CONFLICT_AGENT_CODE_EXISTS]: 409,
  [AhavaErrorCode.CONFLICT_RESOURCE_MODIFIED]: 409,

  [AhavaErrorCode.EXT_PAYSHAP_ERROR]: 502,
  [AhavaErrorCode.EXT_COMPLY_ADVANTAGE_ERROR]: 503,
  [AhavaErrorCode.EXT_AFRICA_TALKING_ERROR]: 503,
  [AhavaErrorCode.EXT_FCM_ERROR]: 503,
  [AhavaErrorCode.EXT_AWS_SECRETS_ERROR]: 500,
  [AhavaErrorCode.EXT_S3_ERROR]: 503,
  [AhavaErrorCode.EXT_SES_ERROR]: 503,

  [AhavaErrorCode.DB_CONNECTION_FAILED]: 503,
  [AhavaErrorCode.DB_TRANSACTION_FAILED]: 500,
  [AhavaErrorCode.DB_DEADLOCK]: 503,
  [AhavaErrorCode.DB_CONSTRAINT_VIOLATION]: 409,
  [AhavaErrorCode.DB_NOT_FOUND]: 404,
  [AhavaErrorCode.DB_QUERY_TIMEOUT]: 504,

  [AhavaErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [AhavaErrorCode.INTERNAL_NOT_IMPLEMENTED]: 501,
  [AhavaErrorCode.INTERNAL_SERVICE_UNAVAILABLE]: 503,
  [AhavaErrorCode.INTERNAL_DEPENDENCY_FAILURE]: 502,
  [AhavaErrorCode.INTERNAL_CONFIG_ERROR]: 500,
};

/**
 * AhavaError — Base error class for all application exceptions
 * Always includes: code, message, statusCode, requestId, timestamp
 */
export class AhavaError extends Error {
  public readonly code: AhavaErrorCode;
  public readonly statusCode: number;
  public readonly requestId?: string;
  public readonly timestamp: Date;
  public readonly details?: Record<string, unknown>;

  constructor(
    code: AhavaErrorCode,
    message: string,
    options?: {
      statusCode?: number;
      requestId?: string;
      details?: Record<string, unknown>;
    }
  ) {
    super(message);
    this.name = "AhavaError";
    this.code = code;
    this.statusCode = options?.statusCode ?? ERROR_CODE_TO_HTTP_STATUS[code] ?? 500;
    this.requestId = options?.requestId;
    this.timestamp = new Date();
    this.details = options?.details;

    // Maintain proper prototype chain
    Object.setPrototypeOf(this, AhavaError.prototype);
  }

  /**
   * Convert to API response format
   */
  toJSON() {
    return {
      success: false,
      error: {
        code: this.code,
        message: this.message,
        statusCode: this.statusCode,
        requestId: this.requestId,
        timestamp: this.timestamp.toISOString(),
        details: this.details,
      },
    };
  }
}

/**
 * Success response wrapper
 */
export interface AhavaSuccessResponse<T = unknown> {
  success: true;
  data: T;
  requestId?: string;
  timestamp?: string;
}

/**
 * Error response wrapper
 */
export interface AhavaErrorResponse {
  success: false;
  error: {
    code: AhavaErrorCode;
    message: string;
    statusCode: number;
    requestId?: string;
    timestamp: string;
    details?: Record<string, unknown>;
  };
}

/**
 * Generic API response
 */
export type AhavaResponse<T = unknown> = AhavaSuccessResponse<T> | AhavaErrorResponse;

/**
 * Utility to create success responses
 */
export function createSuccessResponse<T>(data: T, requestId?: string): AhavaSuccessResponse<T> {
  return {
    success: true,
    data,
    requestId,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Utility to create error responses
 */
export function createErrorResponse(error: AhavaError): AhavaErrorResponse {
  return {
    success: false,
    error: {
      code: error.code,
      message: error.message,
      statusCode: error.statusCode,
      requestId: error.requestId,
      timestamp: error.timestamp.toISOString(),
      details: error.details,
    },
  };
}

export default AhavaError;
