FROM node:20-alpine AS base

# Set working directory
WORKDIR /app

# Install dependencies needed for turbo
RUN apk add --no-cache libc6-compat
RUN npm install -g turbo

# ---------------------------------------------------------
# Builder stage
# ---------------------------------------------------------
FROM base AS builder
ARG APP_NAME

COPY . .
# Run turbo prune to extract just the files needed for the target app
RUN turbo prune --scope=${APP_NAME} --docker

# ---------------------------------------------------------
# Installer stage
# ---------------------------------------------------------
FROM base AS installer
ARG APP_NAME

# First install dependencies
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm install

# Build the project
COPY --from=builder /app/out/full/ .
ENV NEXT_TELEMETRY_DISABLED=1
RUN turbo run build --filter=${APP_NAME}

# ---------------------------------------------------------
# Runner stage
# ---------------------------------------------------------
FROM base AS runner
ARG APP_NAME
ARG APP_DIR
ARG PORT=3000

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=${PORT}

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy nextjs standalone output
COPY --from=installer --chown=nextjs:nodejs /app/${APP_DIR}/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/${APP_DIR}/.next/static ./${APP_DIR}/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/${APP_DIR}/public ./${APP_DIR}/public

USER nextjs

EXPOSE ${PORT}

# Run the standalone server
CMD node ${APP_DIR}/server.js
