-- Migration for Pin, PinAttempt, PinSession tables (BATCH 6 - PIN Concurrency)
-- Generated by Prisma Migrate

-- PinStatus enum
CREATE TYPE "PinStatus" AS ENUM (
  'ACTIVE',
  'LOCKED',
  'DISABLED',
  'PENDING_FIRST_USE'
);

-- PinAttemptStatus enum
CREATE TYPE "PinAttemptStatus" AS ENUM (
  'SUCCESS',
  'FAILED',
  'LOCKED_OUT'
);

-- Pin table: Store PIN hashes (never plaintext)
CREATE TABLE "Pin" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL UNIQUE,
    "walletId" TEXT NOT NULL UNIQUE,
    "pinHash" TEXT NOT NULL, -- bcrypt hash, never plaintext
    "salt" TEXT,
    "status" "PinStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "lastUsedAt" TIMESTAMPTZ,
    "maxAttempts" INTEGER NOT NULL DEFAULT 5,
    "lockoutDurationMinutes" INTEGER NOT NULL DEFAULT 30,
    PRIMARY KEY ("id")
);

-- PinAttempt table: Track verification attempts for rate limiting
CREATE TABLE "PinAttempt" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "ipAddress" TEXT,
    "deviceId" TEXT,
    "status" "PinAttemptStatus" NOT NULL,
    "attemptCount" INTEGER NOT NULL DEFAULT 1,
    "lastAttemptAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "lockedUntil" TIMESTAMPTZ,
    "isLockout" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- PinSession table: Temporary authentication sessions
CREATE TABLE "PinSession" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL UNIQUE,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ipAddress" TEXT,
    "deviceId" TEXT,
    "isValid" BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY ("id")
);

-- Foreign keys
ALTER TABLE "Pin" ADD CONSTRAINT "Pin_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Pin" ADD CONSTRAINT "Pin_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "Wallet"("id") ON DELETE CASCADE;
ALTER TABLE "PinAttempt" ADD CONSTRAINT "PinAttempt_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "PinAttempt" ADD CONSTRAINT "PinAttempt_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "Wallet"("id") ON DELETE CASCADE;
ALTER TABLE "Pin" ADD CONSTRAINT "PinAttempt_pinId_fkey" FOREIGN KEY ("userId", "walletId") REFERENCES "Pin"("userId", "walletId");
ALTER TABLE "PinSession" ADD CONSTRAINT "PinSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "PinSession" ADD CONSTRAINT "PinSession_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "Wallet"("id") ON DELETE CASCADE;

-- Indexes for Pin
CREATE UNIQUE INDEX "Pin_userId_key" ON "Pin"("userId");
CREATE UNIQUE INDEX "Pin_walletId_key" ON "Pin"("walletId");
CREATE INDEX "Pin_status_idx" ON "Pin"("status");
CREATE INDEX "Pin_lastUsedAt_idx" ON "Pin"("lastUsedAt");

-- Indexes for PinAttempt (optimized for rate limiting queries)
CREATE UNIQUE INDEX "PinAttempt_userId_walletId_ipAddress_key" ON "PinAttempt"("userId", "walletId", "ipAddress");
CREATE INDEX "PinAttempt_userId_idx" ON "PinAttempt"("userId");
CREATE INDEX "PinAttempt_walletId_idx" ON "PinAttempt"("walletId");
CREATE INDEX "PinAttempt_ipAddress_idx" ON "PinAttempt"("ipAddress");
CREATE INDEX "PinAttempt_deviceId_idx" ON "PinAttempt"("deviceId");
CREATE INDEX "PinAttempt_lastAttemptAt_idx" ON "PinAttempt"("lastAttemptAt");
CREATE INDEX "PinAttempt_lockedUntil_idx" ON "PinAttempt"("lockedUntil");
CREATE INDEX "PinAttempt_isLockout_idx" ON "PinAttempt"("isLockout");

-- Indexes for PinSession
CREATE UNIQUE INDEX "PinSession_sessionToken_key" ON "PinSession"("sessionToken");
CREATE INDEX "PinSession_userId_idx" ON "PinSession"("userId");
CREATE INDEX "PinSession_walletId_idx" ON "PinSession"("walletId");
CREATE INDEX "PinSession_expiresAt_idx" ON "PinSession"("expiresAt");
CREATE INDEX "PinSession_isValid_idx" ON "PinSession"("isValid");

-- Update triggers for updatedAt
CREATE OR REPLACE FUNCTION update_pin_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_pin_updated_at
  BEFORE UPDATE ON "Pin"
  FOR EACH ROW
  EXECUTE FUNCTION update_pin_updated_at_column();

CREATE OR REPLACE FUNCTION update_pin_attempt_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_pin_attempt_updated_at
  BEFORE UPDATE ON "PinAttempt"
  FOR EACH ROW
  EXECUTE FUNCTION update_pin_attempt_updated_at_column();
