apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-configmap.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - wallet-service.yaml
  - payment-service.yaml
  - kyc-service.yaml
  - notification-service.yaml
  - reporting-service.yaml
  - aml-service.yaml
  - ussd-service.yaml
  - agent-service.yaml
