-- Migration for Saga, SagaStep, SagaReversal tables (BATCH 5 - Saga Reversal)
-- Generated by Prisma Migrate

-- SagaStatus enum
CREATE TYPE "SagaStatus" AS ENUM (
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'REVERSING',
  'REVERSED',
  'PARTIALLY_REVERSED'
);

-- SagaStepStatus enum
CREATE TYPE "SagaStepStatus" AS ENUM (
  'PENDING',
  'COMPLETED',
  'FAILED',
  'SKIPPED',
  'REVERSING',
  'REVERSED'
);

-- Saga table: tracks overall saga execution
CREATE TABLE "Saga" (
    "id" TEXT NOT NULL,
    "sagaType" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL UNIQUE,
    "walletId" TEXT NOT NULL,
    "userId" TEXT,
    "status" "SagaStatus" NOT NULL DEFAULT 'PENDING',
    "currentStep" INTEGER NOT NULL DEFAULT 0,
    "totalSteps" INTEGER NOT NULL DEFAULT 0,
    "startedAt" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    "failedAt" TIMESTAMPTZ,
    "reversedAt" TIMESTAMPTZ,
    "errorMessage" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- SagaStep table: tracks individual steps within a saga
CREATE TABLE "SagaStep" (
    "id" TEXT NOT NULL,
    "sagaId" TEXT NOT NULL,
    "stepNumber" INTEGER NOT NULL,
    "stepType" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "status" "SagaStepStatus" NOT NULL DEFAULT 'PENDING',
    "result" JSONB,
    "errorMessage" TEXT,
    "startedAt" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    "reversalSagaId" TEXT,
    "isReversal" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

-- SagaReversal table: tracks reversal operations
CREATE TABLE "SagaReversal" (
    "id" TEXT NOT NULL,
    "originalSagaId" TEXT NOT NULL UNIQUE,
    "reversalSagaId" TEXT,
    "status" "SagaStatus" NOT NULL DEFAULT 'RUNNING',
    "reason" TEXT,
    "initiatedBy" TEXT,
    "initiatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "completedAt" TIMESTAMPTZ,
    "stepsReversed" INTEGER NOT NULL DEFAULT 0,
    "totalSteps" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Foreign keys
ALTER TABLE "SagaStep" ADD CONSTRAINT "SagaStep_sagaId_fkey" FOREIGN KEY ("sagaId") REFERENCES "Saga"("id") ON DELETE CASCADE;
ALTER TABLE "SagaReversal" ADD CONSTRAINT "SagaReversal_originalSagaId_fkey" FOREIGN KEY ("originalSagaId") REFERENCES "Saga"("id");
ALTER TABLE "SagaStep" ADD CONSTRAINT "SagaStep_reversalSagaId_fkey" FOREIGN KEY ("reversalSagaId") REFERENCES "Saga"("id");

-- Indexes for Saga
CREATE UNIQUE INDEX "Saga_transactionId_key" ON "Saga"("transactionId");
CREATE INDEX "Saga_walletId_idx" ON "Saga"("walletId");
CREATE INDEX "Saga_status_idx" ON "Saga"("status");
CREATE INDEX "Saga_createdAt_idx" ON "Saga"("createdAt");
CREATE INDEX "Saga_sagaType_idx" ON "Saga"("sagaType");

-- Indexes for SagaStep
CREATE UNIQUE INDEX "SagaStep_sagaId_stepNumber_key" ON "SagaStep"("sagaId", "stepNumber");
CREATE INDEX "SagaStep_sagaId_idx" ON "SagaStep"("sagaId");
CREATE INDEX "SagaStep_status_idx" ON "SagaStep"("status");
CREATE INDEX "SagaStep_stepType_idx" ON "SagaStep"("stepType");
CREATE INDEX "SagaStep_createdAt_idx" ON "SagaStep"("createdAt");

-- Indexes for SagaReversal
CREATE UNIQUE INDEX "SagaReversal_originalSagaId_key" ON "SagaReversal"("originalSagaId");
CREATE INDEX "SagaReversal_reversalSagaId_idx" ON "SagaReversal"("reversalSagaId");
CREATE INDEX "SagaReversal_status_idx" ON "SagaReversal"("status");
CREATE INDEX "SagaReversal_initiatedAt_idx" ON "SagaReversal"("initiatedAt");

-- Update triggers for updatedAt
CREATE OR REPLACE FUNCTION update_saga_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_saga_updated_at
  BEFORE UPDATE ON "Saga"
  FOR EACH ROW
  EXECUTE FUNCTION update_saga_updated_at_column();

CREATE OR REPLACE FUNCTION update_saga_step_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_saga_step_updated_at
  BEFORE UPDATE ON "SagaStep"
  FOR EACH ROW
  EXECUTE FUNCTION update_saga_step_updated_at_column();

CREATE OR REPLACE FUNCTION update_saga_reversal_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_saga_reversal_updated_at
  BEFORE UPDATE ON "SagaReversal"
  FOR EACH ROW
  EXECUTE FUNCTION update_saga_reversal_updated_at_column();
