-- Migration for Fee and FeeConfiguration tables (BATCH 4 - Fee Accounting Consistency)
-- Generated by Prisma Migrate

-- FeeType enum
CREATE TYPE "FeeType" AS ENUM (
  'TRANSACTION_FEE',
  'WITHDRAWAL_FEE',
  'DEPOSIT_FEE',
  'SETTLEMENT_FEE',
  'PLATFORM_FEE',
  'AGENT_COMMISSION',
  'SERVICE_FEE',
  'FX_FEE'
);

-- FeeStatus enum
CREATE TYPE "FeeStatus" AS ENUM (
  'PENDING',
  'COMPLETED',
  'REVERSED',
  'REFUNDED'
);

-- Fee table for tracking all fees
CREATE TABLE "Fee" (
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "userId" TEXT,
    "feeType" "FeeType" NOT NULL,
    "amountCents" NUMERIC NOT NULL, -- BIGINT equivalent in PostgreSQL
    "currency" TEXT NOT NULL DEFAULT 'ZAR',
    "status" "FeeStatus" NOT NULL DEFAULT 'PENDING',
    "description" TEXT,
    "reference" TEXT,
    "debitEntryId" TEXT,
    "creditEntryId" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "settledAt" TIMESTAMPTZ,
    PRIMARY KEY ("id")
);

-- FeeConfiguration table for fee rules
CREATE TABLE "FeeConfiguration" (
    "id" TEXT NOT NULL,
    "feeType" "FeeType" NOT NULL UNIQUE,
    "calculationMethod" TEXT NOT NULL, -- PERCENTAGE, FLAT, TIERED
    "baseValue" NUMERIC NOT NULL, -- For PERCENTAGE: 1.5 = 1.5%, For FLAT: amount in cents
    "minFeeCents" NUMERIC NOT NULL DEFAULT 0,
    "maxFeeCents" NUMERIC,
    "tiers" JSONB, -- For TIERED: [{"min": 0, "max": 100000, "rate": 1.5}, ...]
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Indexes for Fee table
CREATE INDEX "Fee_transactionId_idx" ON "Fee"("transactionId");
CREATE INDEX "Fee_walletId_idx" ON "Fee"("walletId");
CREATE INDEX "Fee_feeType_idx" ON "Fee"("feeType");
CREATE INDEX "Fee_status_idx" ON "Fee"("status");
CREATE INDEX "Fee_createdAt_idx" ON "Fee"("createdAt");

-- Indexes for FeeConfiguration table
CREATE INDEX "FeeConfiguration_feeType_idx" ON "FeeConfiguration"("feeType");
CREATE INDEX "FeeConfiguration_isActive_idx" ON "FeeConfiguration"("isActive");

-- Foreign key constraints (optional, can be added if needed)
-- ALTER TABLE "Fee" ADD CONSTRAINT "Fee_debitEntryId_fkey" FOREIGN KEY ("debitEntryId") REFERENCES "LedgerEntry"("id");
-- ALTER TABLE "Fee" ADD CONSTRAINT "Fee_creditEntryId_fkey" FOREIGN KEY ("creditEntryId") REFERENCES "LedgerEntry"("id");

-- Update trigger for updatedAt
CREATE OR REPLACE FUNCTION update_fee_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fee_updated_at
  BEFORE UPDATE ON "Fee"
  FOR EACH ROW
  EXECUTE FUNCTION update_fee_updated_at_column();

CREATE OR REPLACE FUNCTION update_fee_config_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fee_config_updated_at
  BEFORE UPDATE ON "FeeConfiguration"
  FOR EACH ROW
  EXECUTE FUNCTION update_fee_config_updated_at_column();
