-- Migration for QrPayment table (BATCH 3 - QR Payment Idempotency)
-- Generated by Prisma Migrate

CREATE TYPE "QrPaymentStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'EXPIRED');

CREATE TABLE "QrPayment" (
    "id" TEXT NOT NULL,
    "qrCodeId" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "amountCents" NUMERIC NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'ZAR',
    "status" "QrPaymentStatus" NOT NULL DEFAULT 'PENDING',
    "reference" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "expiresAt" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("id")
);

-- Create indexes for idempotency lookups
CREATE UNIQUE INDEX "QrPayment_qrCodeId_key" ON "QrPayment"("qrCodeId");
CREATE UNIQUE INDEX "QrPayment_transactionId_key" ON "QrPayment"("transactionId");
CREATE INDEX "QrPayment_walletId_idx" ON "QrPayment"("walletId");
CREATE INDEX "QrPayment_status_idx" ON "QrPayment"("status");
CREATE INDEX "QrPayment_expiresAt_idx" ON "QrPayment"("expiresAt");

-- Create a function to update the updatedAt timestamp
CREATE OR REPLACE FUNCTION update_qr_payment_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updatedAt
DROP TRIGGER IF EXISTS update_qr_payment_updated_at ON "QrPayment";
CREATE TRIGGER update_qr_payment_updated_at
  BEFORE UPDATE ON "QrPayment"
  FOR EACH ROW
  EXECUTE FUNCTION update_qr_payment_updated_at_column();
