apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../
  - ../../ingress.yaml
  - external-secrets.yaml

namespace: ahava-dev

images:
  - name: ahava/api-gateway
    newTag: dev
  - name: ahava/auth-service
    newTag: dev
  - name: ahava/wallet-service
    newTag: dev
  - name: ahava/payment-service
    newTag: dev
  - name: ahava/kyc-service
    newTag: dev
  - name: ahava/notification-service
    newTag: dev
  - name: ahava/reporting-service
    newTag: dev
  - name: ahava/aml-service
    newTag: dev
  - name: ahava/ussd-service
    newTag: dev
  - name: ahava/agent-service
    newTag: dev

patchesStrategicMerge:
  - ingress-patch.yaml
