apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ahava-aws-secrets
  namespace: ahava
  labels:
    app.kubernetes.io/part-of: ahava-ewallet
spec:
  provider:
    aws:
      service: SecretsManager
      region: af-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: ahava
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_EXTERNAL_SECRETS_ROLE_ARN"
  labels:
    app.kubernetes.io/part-of: ahava-ewallet
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ahava-secrets
  namespace: ahava
  labels:
    app.kubernetes.io/part-of: ahava-ewallet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ahava-aws-secrets
    kind: SecretStore
  target:
    name: ahava-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /ahava/staging/rds-master-password
        property: connection_url
    - secretKey: REDIS_URL
      remoteRef:
        key: /ahava/staging/redis-auth-token
        property: connection_url
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: /ahava/staging/jwt-private-key
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: /ahava/staging/jwt-public-key
    - secretKey: PII_ENCRYPTION_KEY
      remoteRef:
        key: /ahava/staging/pii-encryption-key
    - secretKey: HASH_SALT
      remoteRef:
        key: /ahava/staging/hash-salt
    - secretKey: PAYSHAP_MTLS_CERT
      remoteRef:
        key: /ahava/staging/payshap-mtls-cert
    - secretKey: PAYSHAP_MTLS_KEY
      remoteRef:
        key: /ahava/staging/payshap-mtls-key
    - secretKey: COMPLY_ADVANTAGE_API_KEY
      remoteRef:
        key: /ahava/staging/comply-advantage-api-key
    - secretKey: AFRICAS_TALKING_CREDENTIALS
      remoteRef:
        key: /ahava/staging/africas-talking
    - secretKey: FCM_SERVER_KEY
      remoteRef:
        key: /ahava/staging/fcm-server-key
    - secretKey: SENTRY_DSN
      remoteRef:
        key: /ahava/staging/sentry-dsn
    - secretKey: DATADOG_API_KEY
      remoteRef:
        key: /ahava/staging/datadog-api-key
